(@::def-pkg '((:NAME . "composing")
        (:FULL-NAME . "≈≈∞Ê")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.7")
        (:LOCALE . "chs")
        (:CATEGORY . "≈≈∞Ê")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:FREE . T)
        (:DESCRIPTION . "∏˜÷÷≈≈∞Ê")
        (:URL . "http://atlisp.cn")
        (:FILES "composing"
            "cluster-composing")))
