(@::def-pkg '((:NAME . "al-plate")
        (:FULL-NAME . "ÂÁ°å")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.4")
        (:LOCALE . "chs")
        (:CATEGORY . "»úÐµ")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "ÂÁ°åÕ¹¿ª")
        (:URL . "http://atlisp.cn")
        (:FILES "al-plate")))
