(@::def-pkg '((:NAME . "saw-blade")
        (:FULL-NAME . "æ‚∆¨")
        (:AUTHOR . "VitalGG")
        (:EMAIL . "vitalgg@gmail.com")
        (:VERSION . "0.0.5")
        (:LOCALE . "chs")
        (:CATEGORY . "ª˙–µ")
        (:REQUIRED . "base")
        (:OPENSOURCE . 0)
        (:DESCRIPTION . "ªÊ÷∆æ‚∆¨")
        (:URL . "http://atlisp.cn")
        (:FILES "saw-blade")))
